# This YAML pipeline is configured to run on the 'fe-develop' branch trigger.
# It uses the latest Ubuntu virtual machine image.
# The pipeline defines an npm cache location variable.
# The steps in the pipeline are as follows:
# 1. Checkout the repository without submodules.
# 2. Install 'bun' (a JavaScript runtime) and add it to the PATH.
# 3. Run 'bun install' to install node modules in the 'PreciseAlloy.Frontend' directory.
# 4. Generate a static site using the 'bun run eshn' command.
#
# NOTE: consider pinpoint the version of Bun in you project to avoid breaking changes
# See: https://bun.sh/docs/installation#installing

resources:
  repositories:
    - repository: self
      type: git
      ref: fe-develop

trigger:
  - fe-develop

pool:
  vmImage: ubuntu-latest

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
  - checkout: self
    submodules: false

  - script: |
      curl -fsSL https://bun.sh/install | bash
      echo '##vso[task.prependpath]~/.bun/bin'
    displayName: Install bun
    workingDirectory: PreciseAlloy.Frontend

  - script: |
      bun install
    displayName: Install node modules
    workingDirectory: ./PreciseAlloy.Frontend

  - script: |
      bun run eshn
    displayName: Generate static site
    workingDirectory: PreciseAlloy.Frontend

  - task: AzureStaticWebApp@0
    displayName: Deploy to Azure Static Web App
    inputs:
      app_location: PreciseAlloy.Frontend/dist/static
      api_location: ''
      output_location: ''
      skip_app_build: true
      skip_api_build: true
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
