using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace PreciseAlloy.Utils.SourceGenerators;

/// <summary>
/// Reads <c>wwwroot/assets/hashes.json</c> (supplied via <c>AdditionalFiles</c>)
/// and emits a strongly-typed <c>AssetPaths</c> class containing the cache-busted
/// URL for every known asset. Eliminates per-request dictionary lookups in Razor.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class AssetPathsGenerator : IIncrementalGenerator
{
    private const string HashesFileName = "hashes.json";
    private const string GeneratedNamespace = "PreciseAlloy.Web.Generated";

    private static readonly Regex EntryRegex = new(
        "\"(?<k>[^\"]+)\"\\s*:\\s*\"(?<v>[^\"]*)\"",
        RegexOptions.Compiled);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var hashesFile = context.AdditionalTextsProvider
            .Where(static f => f.Path.Replace('\\', '/').EndsWith("/assets/" + HashesFileName, StringComparison.OrdinalIgnoreCase))
            .Select(static (f, ct) => f.GetText(ct)?.ToString() ?? string.Empty)
            .Collect();

        context.RegisterSourceOutput(hashesFile, static (spc, texts) =>
        {
            string? json = texts.FirstOrDefault(t => !string.IsNullOrWhiteSpace(t));
            var entries = json is null ? new List<(string Path, string Hash)>() : ParseEntries(json);
            var source = Emit(entries);
            spc.AddSource("AssetPaths.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static List<(string Path, string Hash)> ParseEntries(string json)
    {
        var list = new List<(string, string)>();
        foreach (Match m in EntryRegex.Matches(json))
        {
            var key = m.Groups["k"].Value;
            var val = m.Groups["v"].Value;
            if (key.StartsWith("/", StringComparison.Ordinal))
            {
                list.Add((key, val));
            }
        }
        return list;
    }

    private static string Emit(IReadOnlyList<(string Path, string Hash)> entries)
    {
        // Build (propertyName, value, path, widgetStem) tuples; resolve collisions.
        var rows = new List<(string Name, string Value, string Path, string Stem)>(entries.Count);
        var nameCount = new Dictionary<string, int>(StringComparer.Ordinal);

        foreach (var (path, hash) in entries)
        {
            var lastSlash = path.LastIndexOf('/');
            var fileName = lastSlash >= 0 ? path.Substring(lastSlash + 1) : path;

            string baseName;
            string ext;
            string stem;
            string value;

            var widgetMarker = fileName.IndexOf(".0x", StringComparison.Ordinal);
            if (widgetMarker > 0)
            {
                stem = fileName.Substring(0, widgetMarker);
                ext = System.IO.Path.GetExtension(fileName).TrimStart('.');
                baseName = "Widget" + stem;
                value = path; // hash is embedded in filename
            }
            else
            {
                var dot = fileName.LastIndexOf('.');
                baseName = dot >= 0 ? fileName.Substring(0, dot) : fileName;
                ext = dot >= 0 ? fileName.Substring(dot + 1) : string.Empty;
                stem = string.Empty;
                value = string.IsNullOrEmpty(hash) ? path : path + "?v=" + hash;
            }

            var name = ToPascal(baseName) + ToPascal(ext);
            rows.Add((name, value, path, stem));
            nameCount[name] = nameCount.TryGetValue(name, out var c) ? c + 1 : 1;
        }

        var sb = new StringBuilder(8 * 1024);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(GeneratedNamespace).AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated cache-busted asset URLs. Source: <c>wwwroot/assets/hashes.json</c>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class AssetPaths");
        sb.AppendLine("{");

        // Backing arrays (mutable so dev-time refresher can hot-swap values).
        sb.AppendLine("    private static readonly string[] _values =");
        sb.AppendLine("    {");
        foreach (var r in rows) sb.Append("        ").Append(Quote(r.Value)).AppendLine(",");
        sb.AppendLine("    };");
        sb.AppendLine();

        sb.AppendLine("    private static readonly string[] _paths =");
        sb.AppendLine("    {");
        foreach (var r in rows) sb.Append("        ").Append(Quote(r.Path)).AppendLine(",");
        sb.AppendLine("    };");
        sb.AppendLine();

        sb.AppendLine("    private static readonly string[] _widgetStems =");
        sb.AppendLine("    {");
        foreach (var r in rows) sb.Append("        ").Append(Quote(r.Stem)).AppendLine(",");
        sb.AppendLine("    };");
        sb.AppendLine();

        // Properties (skip name collisions to keep API unambiguous).
        var emittedNames = new HashSet<string>(StringComparer.Ordinal);
        for (var i = 0; i < rows.Count; i++)
        {
            var r = rows[i];
            if (nameCount[r.Name] > 1)
            {
                sb.Append("    // Skipped ambiguous name '").Append(r.Name)
                  .Append("' for path '").Append(r.Path).AppendLine("'.");
                continue;
            }
            if (!emittedNames.Add(r.Name))
            {
                continue;
            }

            sb.Append("    /// <summary>").Append(System.Security.SecurityElement.Escape(r.Path)).AppendLine("</summary>");
            sb.Append("    public static string ").Append(r.Name)
              .Append(" => _values[").Append(i).AppendLine("];");
        }

        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Hot-swap entry point for the dev-time file watcher. Re-applies cache-busting");
        sb.AppendLine("    /// values from a freshly parsed <c>hashes.json</c>. Thread-safe for readers");
        sb.AppendLine("    /// because each slot stores an atomic reference assignment.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static void Refresh(System.Collections.Generic.IDictionary<string, string> latestHashes)");
        sb.AppendLine("    {");
        sb.AppendLine("        for (var i = 0; i < _values.Length; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            var stem = _widgetStems[i];");
        sb.AppendLine("            if (stem.Length > 0)");
        sb.AppendLine("            {");
        sb.AppendLine("                var oldPath = _paths[i];");
        sb.AppendLine("                var slash = oldPath.LastIndexOf('/');");
        sb.AppendLine("                var dir = slash >= 0 ? oldPath.Substring(0, slash + 1) : string.Empty;");
        sb.AppendLine("                var ext = System.IO.Path.GetExtension(oldPath);");
        sb.AppendLine("                var prefix = dir + stem + \".0x\";");
        sb.AppendLine("                foreach (var key in latestHashes.Keys)");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (key.StartsWith(prefix, System.StringComparison.Ordinal)");
        sb.AppendLine("                        && key.EndsWith(ext, System.StringComparison.Ordinal))");
        sb.AppendLine("                    {");
        sb.AppendLine("                        _paths[i] = key;");
        sb.AppendLine("                        _values[i] = key;");
        sb.AppendLine("                        break;");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            else");
        sb.AppendLine("            {");
        sb.AppendLine("                _values[i] = latestHashes.TryGetValue(_paths[i], out var hash) && !string.IsNullOrEmpty(hash)");
        sb.AppendLine("                    ? _paths[i] + \"?v=\" + hash");
        sb.AppendLine("                    : _paths[i];");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Quote(string s) =>
        "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static string ToPascal(string segment)
    {
        if (string.IsNullOrEmpty(segment)) return string.Empty;
        var sb = new StringBuilder(segment.Length);
        var upper = true;
        foreach (var ch in segment)
        {
            if (ch == '-' || ch == '_' || ch == '.' || ch == ' ')
            {
                upper = true;
                continue;
            }
            if (!char.IsLetterOrDigit(ch))
            {
                continue;
            }
            sb.Append(upper ? char.ToUpperInvariant(ch) : ch);
            upper = false;
        }
        return sb.ToString();
    }
}
